version: '2'
services:
  gray-mongo:
    image: "mongo:3"
    volumes:
      - \\naujalisdell\Docker\ArchChallenge\ArchChallenge\graylog\data\db:/data/db
  gray-elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - \\naujalisdell\Docker\ArchChallenge\ArchChallenge\graylog\data\elasticsearch:/usr/share/elasticsearch/data
  graylog:
    image: graylog2/server:2.1.1-1
    volumes:
      - \\naujalisdell\Docker\ArchChallenge\ArchChallenge\graylog\data\journal:/usr/share/graylog/data/journal
      - ./config:/usr/share/graylog/data/config
    environment:
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
    links:
      - gray-mongo:mongo
      - gray-elasticsearch:elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201/udp"
      - "1514:1514/udp"